// vue-app/src/components/ChatBox.vue
<script setup>
import { ref, nextTick, watch } from 'vue'
import { v4 as uuidv4 } from 'uuid'

const props = defineProps({
    chats: {
        type: Array,
        default: () => []
    },
    currentUser: {
        type: Object,
        default: () => ({ name: 'Admin User' }) // Mock user
    }
})

const emit = defineEmits(['sendMessage', 'updateMessage'])

const message = ref('')
const chatContainer = ref(null)

const getInitials = (name) => {
    return (name || 'Unknown')
        .split(' ')
        .map(word => word[0])
        .join('')
        .toUpperCase()
        .slice(0, 2)
}

const formatDate = (dateString) => {
    if (!dateString) return ''
    const date = new Date(dateString)
    return date.toLocaleString('en-US', {
        month: 'short',
        day: 'numeric',
        hour: 'numeric',
        minute: 'numeric',
        hour12: true
    })
}

const sendMessage = () => {
    if (!message.value.trim()) return

    const newChat = {
        id: uuidv4(),
        message: message.value.trim(),
        date: new Date().toISOString(),
        sender: props.currentUser.name,
        completed: false
    }

    emit('sendMessage', newChat)
    message.value = ''
    scrollToBottom()
}

const toggleComplete = (chat) => {
    emit('updateMessage', { ...chat, completed: !chat.completed })
}

const scrollToBottom = async () => {
    await nextTick()
    if (chatContainer.value) {
        chatContainer.value.scrollTop = chatContainer.value.scrollHeight
    }
}

watch(() => props.chats.length, scrollToBottom)
</script>

<template>
    <div class="chat-box d-flex flex-column glass-card rounded-lg overflow-hidden"
        style="height: 400px; border: 1px solid rgba(255,255,255,0.1)">
        <!-- Header -->
        <div class="pa-3 bg-surface border-b d-flex justify-space-between align-center">
            <span class="text-subtitle-2 font-weight-bold">Project Chat</span>
            <v-chip size="x-small" color="primary" variant="flat">
                {{chats.filter(c => !c.completed).length}} Pending
            </v-chip>
        </div>

        <!-- Messages Area -->
        <div ref="chatContainer" class="flex-grow-1 overflow-y-auto pa-4 d-flex flex-column gap-3 bg-transparent">
            <div v-if="chats.length === 0" class="text-center text-medium-emphasis my-auto">
                <v-icon size="large" class="mb-2">mdi-message-text-outline</v-icon>
                <p class="text-caption">No messages yet. Start the conversation!</p>
            </div>

            <div v-for="chat in chats" :key="chat.id || chat.date" class="d-flex w-100 gap-2"
                :class="chat.sender === currentUser.name ? 'flex-row-reverse' : ''">
                <!-- Avatar -->
                <v-avatar size="32" :color="chat.sender === currentUser.name ? 'primary' : 'secondary'">
                    <span class="text-caption font-weight-bold text-white">{{ getInitials(chat.sender) }}</span>
                </v-avatar>

                <!-- Message Bubble -->
                <div class="d-flex flex-column" style="max-width: 80%">
                    <div class="pa-3 rounded-lg text-body-2" :class="[
                        chat.sender === currentUser.name ? 'bg-primary text-white rounded-tr-0' : 'bg-surface text-high-emphasis rounded-tl-0',
                        chat.completed ? 'text-decoration-line-through opacity-50' : ''
                    ]" style="border: 1px solid rgba(255,255,255,0.1)">
                        {{ chat.message }}
                    </div>
                    <div class="d-flex align-center gap-2 mt-1 px-1">
                        <span class="text-caption text-disabled" style="font-size: 10px">{{ formatDate(chat.date)
                            }}</span>
                        <v-checkbox-btn :model-value="chat.completed" @update:model-value="toggleComplete(chat)"
                            density="compact" color="success" hide-details
                            style="height: 20px; width: 20px"></v-checkbox-btn>
                    </div>
                </div>
            </div>
        </div>

        <!-- Input Area -->
        <div class="pa-2 bg-surface border-t d-flex align-center gap-2">
            <v-text-field v-model="message" placeholder="Type a message..." variant="solo" density="compact"
                hide-details bg-color="transparent" class="glow-input" @keyup.enter="sendMessage"></v-text-field>
            <v-btn icon="mdi-send" size="small" color="primary" class="glow-btn" @click="sendMessage"></v-btn>
        </div>
    </div>
</template>

<style scoped>
.gap-2 {
    gap: 8px;
}

.gap-3 {
    gap: 12px;
}

/* Custom scrollbar for chat */
.overflow-y-auto::-webkit-scrollbar {
    width: 6px;
}

.overflow-y-auto::-webkit-scrollbar-thumb {
    background: rgba(255, 255, 255, 0.2);
    border-radius: 3px;
}
</style>

// src/components/ProjectDashboard/ChatBox.jsx
import React, { useState, useRef, useEffect } from "react";
import { Box, TextField, IconButton, Paper, Typography, Avatar, Tooltip, Checkbox } from "@mui/material";
import SendIcon from "@mui/icons-material/Send";
import useAuth from "hooks/useAuth";
import { v4 as uuidv4 } from "uuid";

const getInitials = (name) => {
  return name
    .split(" ")
    .map((word) => word[0])
    .join("")
    .toUpperCase();
};

const formatDate = (dateString) => {
  const date = new Date(dateString);
  const now = new Date();
  const isToday = date.toDateString() === now.toDateString();
  const isCurrentYear = date.getFullYear() === now.getFullYear();

  if (isToday) {
    return date.toLocaleTimeString("en-US", {
      hour: "numeric",
      minute: "numeric",
      hour12: true,
    });
  } else if (isCurrentYear) {
    return date.toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      hour: "numeric",
      minute: "numeric",
      hour12: true,
    });
  } else {
    return date.toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
      hour: "numeric",
      minute: "numeric",
      hour12: true,
    });
  }
};

const ChatBox = ({ chats = [], onSendMessage, onMessageComplete }) => {
  const [newMessage, setNewMessage] = useState("");
  const chatsEndRef = useRef(null);
  const chatBoxRef = useRef(null);
  const { user } = useAuth();

  const scrollToBottom = () => {
    if (chatBoxRef.current) {
      chatBoxRef.current.scrollTop = chatBoxRef.current.scrollHeight;
    }
  };

  useEffect(() => {
    scrollToBottom();
  }, [chats]);

  const handleSendMessage = (e) => {
    e.preventDefault();
    if (newMessage.trim()) {
      onSendMessage({
        message: newMessage.trim(),
        date: new Date().toISOString(),
        sender: user?.name || "Unknown User",
        completed: false,
        id: uuidv4(),
      });

      setNewMessage("");
    }
  };

  const handleMessageSelect = (chat, ischecked) => {
    chat.completed = ischecked;
    onMessageComplete(chat);
  };

  return (
    <>
      <Typography variant="h6" sx={{ mb: 1 }}>
        Project Chat{" "}
        {(() => {
          const pendingCount = chats.filter((chat) => !chat.completed).length;
          if (chats.length === 0) return "";
          if (pendingCount === 0) return "(All Complete)";
          return `(${pendingCount} ${pendingCount === 1 ? "Item" : "Items"} Pending)`;
        })()}
      </Typography>
      <Box
        sx={{
          display: "flex",
          flexDirection: "column",
          height: "400px",
          border: "1px solid #e0e0e0",
          borderRadius: 1,
          overflow: "hidden",
          backgroundColor: "#fff",
          width: "100%",
        }}>
        {/* Chats Container */}
        <Paper
          ref={chatBoxRef}
          sx={{
            flex: 1,
            overflow: "auto",
            p: 2,
            display: "flex",
            flexDirection: "column",
            gap: 1,
            backgroundColor: "#f8f9fa",
          }}>
          {chats.map((chat, index) => (
            <Box
              key={index}
              sx={{
                display: "flex",
                flexDirection: "column",
                gap: 0.5,
                position: "relative",
              }}>
              <Box
                sx={{
                  display: "flex",
                  gap: 1,
                  alignItems: "flex-middle",
                }}>
                <Tooltip title={chat.sender} arrow>
                  <Avatar
                    sx={{
                      width: 24,
                      height: 24,
                      fontSize: "0.7rem",
                      bgcolor: chat.sender === user?.name ? "primary.main" : "secondary.main",
                    }}>
                    {getInitials(chat.sender)}
                  </Avatar>
                </Tooltip>
                <Paper
                  elevation={1}
                  sx={{
                    p: 1.5,
                    backgroundColor: chat.completed ? "#e8f5e9" : chat.sender === user?.name ? "#e3f2fd" : "#fff",
                    borderRadius: 2,
                    wordBreak: "break-word",
                    boxShadow: "0 1px 2px rgba(0,0,0,0.1)",
                    width: "100%",
                    border: "1px solid",
                    borderColor: chat.completed ? "success.light" : chat.sender === user?.name ? "primary.light" : "grey.200",
                    textDecoration: chat.completed ? "line-through" : "none",
                    textDecorationColor: "rgba(0, 0, 0, 0.3)",
                  }}>
                  <Typography variant="body2">{chat.message}</Typography>
                </Paper>
                <Checkbox
                  size="small"
                  checked={chat.completed}
                  onChange={(e) => handleMessageSelect(chat, e.target.checked)}
                  sx={{
                    p: 0,
                    "&.Mui-checked": {
                      color: "primary.main",
                    },
                  }}
                />
              </Box>
              <Typography
                variant="caption"
                sx={{
                  color: "text.secondary",
                  position: "absolute",
                  top: -4,
                  right: 0,
                  fontSize: "0.65rem",
                  backgroundColor: "#f8f9fa",
                  px: 0.5,
                }}>
                {formatDate(chat.date)}
              </Typography>
            </Box>
          ))}
          <div ref={chatsEndRef} />
        </Paper>

        {/* Message Input */}
        <Box
          component="form"
          onSubmit={handleSendMessage}
          sx={{
            p: 1.5,
            borderTop: "1px solid #e0e0e0",
            display: "flex",
            gap: 1,
            backgroundColor: "#fff",
          }}>
          <TextField
            fullWidth
            multiline
            maxRows={3}
            size="small"
            placeholder="Type a message..."
            value={newMessage}
            onChange={(e) => setNewMessage(e.target.value)}
            sx={{
              backgroundColor: "#fff",
              "& .MuiOutlinedInput-root": {
                borderRadius: 2,
                minHeight: "40px",
                maxHeight: "120px",
              },
            }}
          />
          <IconButton
            type="submit"
            color="primary"
            disabled={!newMessage.trim()}
            sx={{
              backgroundColor: "primary.main",
              color: "white",
              "&:hover": {
                backgroundColor: "primary.dark",
              },
            }}>
            <SendIcon />
          </IconButton>
        </Box>
      </Box>
    </>
  );
};

export default ChatBox;
